{
 "title": "Devops client (by menshikov_a)",
 "description": "Мой крутой дешборд",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Requests",
   "type": "timeseries",
   "description": "Total RPS",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by() (rate(requested_total{job=\"devops-server-balancer\"}[$__rate_interval]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Request timings",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(response_time_bucket{job=\"devops-server-balancer\"}[$__rate_interval])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(response_time_bucket{job=\"devops-server-balancer\"}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(response_time_bucket{job=\"devops-server-balancer\"}[$__rate_interval])))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(response_time_bucket{job=\"devops-server-balancer\"}[$__rate_interval])))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Requests with image",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(image_request_total{job=\"devops-server-balancer\", need_image=\"image_requested\"}[$__rate_interval])) * 100) / (sum(rate(requests_total{type=\"requested\"}[$__rate_interval])))",
     "legendFormat": "Needs image"
    }
   ]
  },
  {
   "title": "Trafficlight requests",
   "type": "timeseries",
   "description": "Total requests for each trafficlight",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(requested_types_total{type=\"traffic1\", job=\"devops-server-balancer\"}[$__rate_interval]))",
     "legendFormat": "trafficlight1"
    },
    {
     "expr": "sum(rate(requested_types_total{type=\"traffic2\", job=\"devops-server-balancer\"}[$__rate_interval]))",
     "legendFormat": "trafficlight2"
    },
    {
     "expr": "sum(rate(requested_types_total{type=\"traffic3\", job=\"devops-server-balancer\"}[$__rate_interval]))",
     "legendFormat": "trafficlight3"
    }
   ]
  },
  {
   "title": "Percent for each trafficlight",
   "type": "stat",
   "description": "Percent of requests for each trafficilight",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(requested_types_total{type=\"traffic1\"}[$__rate_interval])) * 100) / (sum(rate(requests_total{type=\"requested\"}[$__rate_interval])))",
     "legendFormat": "trafficlight1"
    },
    {
     "expr": "(sum(rate(requested_types_total{type=\"traffic2\"}[$__rate_interval])) * 100) / (sum(rate(requests_total{type=\"requested\"}[$__rate_interval])))",
     "legendFormat": "trafficlight2"
    },
    {
     "expr": "(sum(rate(requested_types_total{type=\"traffic3\"}[$__rate_interval])) * 100) / (sum(rate(requests_total{type=\"requested\"}[$__rate_interval])))",
     "legendFormat": "trafficlight3"
    }
   ]
  }
 ]
}